### ISSUE TITLE
Eclipse 2022-12+ creates incomplete/defective eMoflon::IBeX updatesite

### ISSUE THREAD

**Issue by maxkratz** [eMoflon/emoflon-ibex-deployment#4]
When building an Eclipse updatesite for eMoflon::IBeX with **Eclipse 2022-12**, the plug-ins can be installed in another instance but building the eMoflon::IBeX test workspace is **not** possible. The following error message pops up immediately:

![image](https://user-images.githubusercontent.com/20956405/223436387-60b47b81-523f-4f25-8139-485f351c7ee7.png)

Observations made so far:
- The runtime workspace is not affected, only the deployed version.
- It hasn't something to do with our Eclipse pipeline build; the error also occurs if one sets up both workspaces with vanilla Eclipse instances downloaded from https://eclipse.org.
- Updatesite built on the latest Eclipse 2022-09 (from our CI: https://github.com/eMoflon/emoflon-ibex-eclipse-build/releases/tag/v1.0.0.202210111747) and deployed in Eclipse 2022-12 does **not** reproduce the error -> It seems that Eclipse 2022-12 is unable to produce a complete functional updatesite.
- The produced updatesite artifact is a few KiB smaller when built with Eclipse 2022-12 (compared to the artifact built with Eclipse 2022-09).

**Comment by maxkratz** [comment]
A noticeable difference between Eclipse 2022-09 and 2022-12:
- Xtext v2.28.0 vs Xtext v2.30.0
- Xtend was updated, to

**Comment by maxkratz** [comment]
Update:
- Eclipse 2022-09 with the newer Xtext version (v2.30.0) can build a functioning updatesite.

**Comment by maxkratz** [comment]
Update:
- Eclipse 2023-03 (built by the [CI pipeline](https://github.com/eMoflon/emoflon-ibex-eclipse-build/actions/runs/4436817590)) is also unable to produce a functional updatesite.

**Comment by maxkratz** [comment]
Update:
- Eclipse 2023-06 M3 (with manually installed packages) is also unable to produce a functional updatesite.

**Comment by maxkratz** [comment]
Update:

- The file size of the produced `*.jar` files differ (when compared to a working updatesite)
- Installing a broken eMoflon::IBeX into a fresh Eclipse and then starting a runtime workspace with debugging enabled showed some error messages. The first message was about `PluginXmlUpdater.java`.
- We patched the broken `*.class` file for this class and got another error:
```
java.lang.NoSuchMethodError: 'org.w3c.dom.Document org.moflon.core.utilities.XMLUtils.parseXmlDocument(java.lang.String)'
	at org.moflon.core.plugins.manifest.PluginXmlUpdater.run(PluginXmlUpdater.java:103)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2405)
	at org.gervarro.eclipse.workspace.util.WorkspaceTask.executeInCurrentThread(WorkspaceTask.java:53)
	at org.moflon.core.plugins.manifest.PluginXmlUpdater.updatePluginXml(PluginXmlUpdater.java:91)
	at org.moflon.emf.build.MoflonEmfBuilder.buildEcoreFiles(MoflonEmfBuilder.java:107)
	at org.moflon.emf.build.MoflonEmfBuilder.build(MoflonEmfBuilder.java:67)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:1020)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:247)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:392)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:395)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:506)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:454)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:536)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:524)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:420)
	at org.moflon.core.build.ProjectBuilderTask.run(ProjectBuilderTask.java:57)
	at org.gervarro.eclipse.workspace.util.WorkspaceTaskJob.runInWorkspace(WorkspaceTaskJob.java:32)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
- Eclipse produces Java `*.class` files within the updatesite that contain error messages. Example:
```
����=."org/moflon/core/utilities/XMLUtilsjava/lang/Object<init>()VCode	java/lang/Error
Unresolved compilation problems: 
	The package javax.xml.parsers is accessible from more than one module: <unnamed>, java.xml
	The package javax.xml.parsers is accessible from more than one module: <unnamed>, java.xml
	The package javax.xml.parsers is accessible from more than one module: <unnamed>, java.xml
	The package javax.xml.transform is accessible from more than one module: <unnamed>, java.xml
	The package javax.xml.transform is accessible from more than one module: <unnamed>, java.xml
	The package javax.xml.transform is accessible from more than one module: <unnamed>, java.xml
	The package javax.xml.transform is accessible from more than one module: <unnamed>, java.xml
	The package javax.xml.transform is accessible from more than one module: <unnamed>, java.xml
	The package javax.xml.transform.dom is accessible from more than one module: <unnamed>, java.xml
	The package javax.xml.transform.stream is accessible from more than one module: <unnamed>, java.xml
	The package javax.xml.xpath is accessible from more than one module: <unnamed>, java.xml
	The package javax.xml.xpath is accessible from more than one module: <unnamed>, java.xml
	The package javax.xml.xpath is accessible from more than one module: <unnamed>, java.xml
	The package javax.xml.xpath is accessible from more than one module: <unnamed>, java.xml
	The package org.w3c.dom is accessible from more than one module: <unnamed>, java.xml
	The package org.w3c.dom is accessible from more than one module: <unnamed>, java.xml
	The package org.w3c.dom is accessible from more than one module: <unnamed>, java.xml
	The package org.xml.sax is accessible from more than one module: <unnamed>, java.xml
	Document cannot be resolved to a type
	Transformer cannot be resolved to a type
	TransformerFactory cannot be resolved
	OutputKeys cannot be resolved to a variable
	OutputKeys cannot be resolved to a variable
	StreamResult cannot be resolved to a type
	StreamResult cannot be resolved to a type
	DOMSource cannot be resolved to a type
	DOMSource cannot be resolved to a type
	TransformerFactoryConfigurationError cannot be resolved to a type
	No exception of type Object can be thrown; an exception type must be a subclass of Throwable
	TransformerException cannot be resolved to a type
	The constructor Status(int, String, String, Object) is undefined
	Document cannot be resolved to a type
	DocumentBuilderFactory cannot be resolved to a type
	DocumentBuilderFactory cannot be resolved
	DocumentBuilder cannot be resolved to a type
	Document cannot be resolved to a type
	ParserConfigurationException cannot be resolved to a type
	No exception of type Object can be thrown; an exception type must be a subclass of Throwable
	SAXException cannot be resolved to a type
	XPathExpressionException cannot be resolved to a type
	The constructor Status(int, String, String, Object) is undefined
	Document cannot be resolved to a type
	XPathExpressionException cannot be resolved to a type
	XPath cannot be resolved to a type
	XPathFactory cannot be resolved
	NodeList cannot be resolved to a type
	NodeList cannot be resolved to a type
	XPathConstants cannot be resolved to a variable
	Node cannot be resolved to a type
	Document cannot be resolved to a type
	The method parseXmlDocument(String) from the type XMLUtils refers to the missing type Document


(Ljava/lang/String;)VLineNumberTableLocalVariableTablethis$Lorg/moflon/core/utilities/XMLUtils;formatXmlStringI(LDocument;Lorg/eclipse/core/runtime/IProgressMonitor;)Ljava/lang/String;
Exceptions&org/eclipse/core/runtime/CoreException�Unresolved compilation problems: 
	Document cannot be resolved to a type
	Transformer cannot be resolved to a type
	TransformerFactory cannot be resolved
	OutputKeys cannot be resolved to a variable
	OutputKeys cannot be resolved to a variable
	StreamResult cannot be resolved to a type
	StreamResult cannot be resolved to a type
	DOMSource cannot be resolved to a type
	DOMSource cannot be resolved to a type
	TransformerFactoryConfigurationError cannot be resolved to a type
	No exception of type Object can be thrown; an exception type must be a subclass of Throwable
	TransformerException cannot be resolved to a type
	The constructor Status(int, String, String, Object) is undefined
parseXmlDocument(Ljava/lang/String;)LDocument;;Unresolved compilation problems: 
	Document cannot be resolved to a type
	DocumentBuilderFactory cannot be resolved to a type
	DocumentBuilderFactory cannot be resolved
	DocumentBuilder cannot be resolved to a type
	Document cannot be resolved to a type
	ParserConfigurationException cannot be resolved to a type
	No exception of type Object can be thrown; an exception type must be a subclass of Throwable
	SAXException cannot be resolved to a type
	XPathExpressionException cannot be resolved to a type
	The constructor Status(int, String, String, Object) is undefined
dropWhitespaceNodesFromTree
(LDocument;)V!XPathExpressionException#gUnresolved compilation problems: 
	Document cannot be resolved to a type
	XPathExpressionException cannot be resolved to a type
	XPath cannot be resolved to a type
	XPathFactory cannot be resolved
	NodeList cannot be resolved to a type
	NodeList cannot be resolved to a type
	XPathConstants cannot be resolved to a variable
	Node cannot be resolved to a type
(Ljava/io/File;)LDocument;&java/io/IOException(�Unresolved compilation problems: 
	Document cannot be resolved to a type
	The method parseXmlDocument(String) from the type XMLUtils refers to the missing type Document

SourceFile
XMLUtils.java,DocumentMissingTypes!4
�Y
��
	*
�Y��'	*
�Y��O	 *
�Y"��_	$%*
�Y'��t)*-+ 
```
- Our current idea is that one of the dependencies in eMoflon also brings their own XML-related namespace with them: `The package org.xml.sax is accessible from more than one module: <unnamed>, java.xml`
- We brought it down to the graph stream library:

![image](https://github.com/eMoflon/emoflon-ibex-deployment/assets/20956405/a276b9ed-f3f7-4f29-b9c4-612065d50ddb)

**Comment by maxkratz** [comment]
In a deployed environment:
![image](https://github.com/eMoflon/emoflon-ibex-deployment/assets/20956405/6559eb2d-dc15-48b9-9650-192db4870224)
